# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171112_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.Truck'),
        ),
    ]
