# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:43
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171021_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Start time for opening')),
                ('end_time', models.DateTimeField(default=api.models.hour_later, help_text='End time for opening')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Truck')),
            ],
        ),
    ]
