# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_truckrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Truck')),
            ],
        ),
    ]
