# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:32
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(default=api.models.round_up_time, help_text='Start time for opening'),
        ),
    ]
